<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Magic_Mirror</RootNamespace>
	<Version>1.0.0</Version>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>MagicMirror.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="MagicMirror.ico" />
  </ItemGroup>

</Project>